pipeline {
    agent any

    environment {
        REGISTRY = "localhost:5000"
        PROJECT = "microops"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'jenkinstest', url: 'https://github.com/VaibhavPithadiya/micro-ops-hub.git'
            }
        }

        stage('Build Images') {
            steps {
                sh 'bash ci-cd/jenkins/scripts/build-images.sh'
            }
        }

        stage('Security Scan') {
            steps {
                sh 'bash ci-cd/jenkins/scripts/trivy-scan.sh'
            }
        }

        stage('Push to Registry') {
            steps {
                sh 'bash ci-cd/jenkins/scripts/push-images.sh'
            }
        }

        stage('Deploy (docker-compose)') {
            steps {
                sh 'bash ci-cd/jenkins/scripts/deploy-compose.sh'
            }
        }
    }

    post {
        success {
            echo "✅ Pipeline completed successfully!"
        }
        failure {
            echo "❌ Pipeline failed. Check logs."
        }
    }
}
